# Copyright (c) 2024, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ARG BASE_IMAGE=vllm/vllm-openai:v0.7.0

# build an image that includes only the nemo dependencies, ensures that dependencies
# are included first for optimal caching, and useful for building a development
# image (by specifying build target as `nemo-deps`)
FROM ${BASE_IMAGE} AS vllm-deps

# install vllm dependencies
WORKDIR /opt

ARG VLLM_HASH=v0.7.0

RUN git clone https://github.com/vllm-project/vllm.git && \
  cd vllm && \
  git checkout ${VLLM_HASH} && \
  pip install -e . && \
  cd ..



WORKDIR /opt

# Set environment variables for mounted HF Cache
RUN [[ -d /cache/huggingface/ ]] || mkdir -p /cache/huggingface/
# Add VLLM to PYTHONPATH
ENV PYTHONPATH=/opt/vllm:$PYTHONPATH
ENV HF_HOME=/cache/huggingface
ENV TRANSFORMERS_CACHE=/cache/huggingface/transformers
ENV HUGGINGFACE_HUB_CACHE=/cache/huggingface/hub
ENV HF_DATASETS_CACHE=/cache/huggingface/datasets
