FROM vllm/vllm-openai:v0.10.1.1

# adding editable vllm installation to allow overriding python code with a custom mount
# this overides the installation in the original conainer 
RUN cd /opt && git clone https://github.com/vllm-project/vllm.git && cd vllm && git checkout main && VLLM_USE_PRECOMPILED=1 pip install -e .