# Copyright (c) 2024, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# TODO: find a way to reuse vllm docker directly

FROM nvcr.io/nvidia/pytorch:24.07-py3

RUN pip install git+https://github.com/OpenRLHF/OpenRLHF.git

ARG FLASHINFER_URL=https://github.com/flashinfer-ai/flashinfer/releases/download/v0.2.0.post1/flashinfer-0.2.0.post1+cu121torch2.4-cp310-cp310-linux_x86_64.whl
RUN pip install $FLASHINFER_URL

RUN pip install vllm==0.6.6.post1

# Install requirements
RUN pip install geventhttpclient outlines sentencepiece transformers>=4.45.2 sentence-transformers>=2.2.2 && \
    pip install "megablocks==0.5.1"

RUN pip install opencv-fixer==0.2.5 && python -c "from opencv_fixer import AutoFix; AutoFix()"

WORKDIR /workspace