# Copyright (c) 2024, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# copied from https://openrlhf.readthedocs.io/en/latest/quick_start.html#one-click-installation-script-of-nvidia-docker

# Build instructions:
# DOCKER_BUILDKIT=1 docker build . -f dockerfiles/Dockerfile.openrlhf -t gitlab-master.nvidia.com/smajumdar/nemo_containers/nemo-skills-openrlhf:0.5.0 --progress=plain

# Push
# docker push gitlab-master.nvidia.com/smajumdar/nemo_containers/nemo-skills-openrlhf:0.5.0

FROM nvcr.io/nvidia/pytorch:24.07-py3

RUN apt-get update

RUN pip uninstall xgboost transformer_engine flash_attn -y

WORKDIR /opt
ARG COMMIT=956b5adfbd3d360ce43c0c951c4275df37d6dddc
RUN cd /opt && \
    git clone https://github.com/OpenRLHF/OpenRLHF.git && \
    cd OpenRLHF && \
    git checkout $COMMIT && \
    pip install -e .[vllm_latest]

RUN pip install opencv-fixer==0.2.5 && python -c "from opencv_fixer import AutoFix; AutoFix()"

WORKDIR /workspace
