cluster: dfw
base_output_dir: "/workspace/opensciencereasoning/gpt-oss"
expname: "gpt-oss-generate-solutions"
suffix: "limo_train_preparation"  # Suffix for experiment names
dataset_name: "limo_train"  # Optional dataset name for id generation
is_mcq: False



# Input file for the first stage (generate_solutions)
# It must include the field "problem"
# All the data in this file will be processed with the same prompt
# Make sure the problems fit the prompt you are using
input_file: "/ebakhturina/data/stem_v2_seed_data/limo_train.jsonl"

# Can define initial dependency for the `generate_solutions` stage to run after
initial_dependency: None
initial_dependency: None

# Define the full sequence of stages for this mode
pipeline_stages:
  - filter_problems          # Filter problems based on format
  - decontaminate            # Decontaminate problems
  - topics_labeling          # Label topics and subtopics
  - difficulty_estimation    # Estimate difficulty of problems

# Directory structure configuration
directories:
  step-0-filter-problems: ${base_output_dir}/solution-sdg/step-0-filter-problems
  step-1-decontaminate: ${base_output_dir}/solution-sdg/step-1-decontaminate
  step-2-topics-labeling: ${base_output_dir}/solution-sdg/step-2-topics-labeling
  step-3-difficulty-estimation: ${base_output_dir}/solution-sdg/step-3-difficulty-estimation

# Stage-specific configurations
stages:
  filter_problems:
    output_dir: ${directories.step-0-filter-problems}
    input_file: ${input_file}
    dataset_name: ${dataset_name}
    is_mcq: ${is_mcq}
    remove_images: True
    num_options: 4
    option_format_regex: null
    deduplicate: True
  
  decontaminate:
    output_dir: ${directories.step-1-decontaminate}
    input_file: ${directories.step-0-filter-problems}/final_result.jsonl
    test_sets:
      - ["hle", "text"]
      - ["mmlu", "test"]
      - ["mmlu-pro", "test"]
      - ["gpqa", "diamond"]
    model: /hf_models/Qwen2.5-32B-Instruct
    server_type: sglang
    server_gpus: 1
    server_nodes: 1
    dependent_jobs: 1
    num_chunks: 20
    dependencies:
      - filter_problems

  topics_labeling:
    output_dir: ${directories.step-2-topics-labeling}
    input_file: ${directories.step-1-decontaminate}/final_result.jsonl
    model: /hf_models/Qwen2.5-32B-Instruct
    dependencies:
      - decontaminate
    server_type: sglang
    server_gpus: 8
    server_nodes: 1
    dependent_jobs: 1
    num_chunks: 5
    generation_keys:
      - topic
      - subtopic
    few_shots_name: stem_topics
    topic:
      - Mathematics
      - Chemistry
      - Physics
      - Biology
    subtopic:
      Chemistry:
        - Organic Chemistry
        - Inorganic Chemistry
        - General Chemistry
      Physics:
        - Quantum Mechanics
        - Classical Mechanics
        - General Physics
        - Relativistic Mechanics
        - Electromagnetism and Photonics
        - Optics and Acoustics
        - Condensed Matter Physics
        - High-energy Particle Physics
        - Astrophysics
      Biology:
        - Genetics
        - Molecular Biology
        - General Biology

    
  difficulty_estimation:
    output_dir: ${directories.step-3-difficulty-estimation}
    input_file: ${directories.step-0-filter-problems}/final_result.jsonl 
    is_mcq: ${is_mcq}
    mcq_prompt_config: "aai/mcq-4choices"
    openq_prompt_config: "generic/general-boxed"
    tokens_to_generate: 16000
    num_random_seeds: 5

    generation_kwargs:
      model: /hf_models/Qwen3-30B-A3B
      server_type: vllm
      server_gpus: 8
      server_nodes: 2
      num_random_seeds: ${stages.difficulty_estimation.num_random_seeds}
      num_chunks: 5  
    
    judge_kwargs:
      model: /hf_models/Qwen2.5-32B-Instruct
      server_type: vllm
      server_gpus: 8
      server_nodes: 2
      num_random_seeds: ${stages.difficulty_estimation.num_random_seeds}
      num_chunks: 5
    
    dependencies:
      - decontaminate
      


